### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by darklord1807** [JavaOpenCVBook/code#6]
Hello,

Is there any new maven dependency for the latest version of OpenCV?

Thanks

**Comment by dannyxyz22** [comment]
Hi,

it's been a while since I don't update it :(

So, I just uploaded the 3.3.0 version for windows. Just make sure you update your poms to (64-bits):

	 <dependency>
    	<groupId>org.javaopencvbook</groupId>
    	<artifactId>opencvjar</artifactId>
    	<version>3.3.0</version>    	     
    </dependency>
	
	<dependency>
		<groupId>org.javaopencvbook</groupId>
		<artifactId>opencvjar-runtime</artifactId>
		<version>3.3.0</version>
		<classifier>natives-windows-x86_64</classifier>
	</dependency>

Or, if you are using 32 bits:
	 <dependency>
    	<groupId>org.javaopencvbook</groupId>
    	<artifactId>opencvjar</artifactId>
    	<version>3.3.0</version>    	     
    </dependency>
	
	<dependency>
		<groupId>org.javaopencvbook</groupId>
		<artifactId>opencvjar-runtime</artifactId>
		<version>3.3.0</version>
		<classifier>natives-windows-x86</classifier>
	</dependency>

Please, make some test to see if it's working. I just made a successful run with 64 bit OpenCV 3.3.0.
Have a good one!

**Comment by dannyxyz22** [comment]
It seems to be working for windows, I'll close the issue.
